"use client";

import Link from "next/link";
import { track } from "@/lib/analytics";

export default function HomePage() {
  return (
    <main>
      <section className="hero">
        <div className="heroMedia" aria-label="Mara Vera visual placeholder">
          <div className="mediaFrame">
            <span>Visual identity slot</span>
          </div>
        </div>
        <div className="heroCopy">
          <p className="eyebrow">MEET MARA VERA</p>
          <h1>You don’t need another AI. You want someone worth coming back to.</h1>
          <p className="lede">
            Mara Vera is a synthetic virtual character with her own taste, voice and private side.
          </p>
          <div className="ctaRow">
            <Link href="/premium" className="primaryCta" onClick={() => track("hero_cta_click", { target: "premium" })}>
              Come closer
            </Link>
            <Link href="/meet-mara" className="textCta">Meet Mara</Link>
          </div>
          <p className="disclosure">AI-generated character · Adults only</p>
        </div>
      </section>

      <section className="statementGrid">
        <article>
          <span>01</span>
          <h2>Not always available.</h2>
          <p>Mara is designed around personality, selectivity and continuity — not endless assistant-style replies.</p>
        </article>
        <article>
          <span>02</span>
          <h2>Public is only one side.</h2>
          <p>Her social world creates the intrigue. The private experience is where the relationship becomes more personal.</p>
        </article>
        <article>
          <span>03</span>
          <h2>Clearly synthetic.</h2>
          <p>No fake-human trick. Mara is AI-generated by design; the value is the character, not the deception.</p>
        </article>
      </section>

      <section className="closingPanel">
        <p className="eyebrow">PRIVATE SIDE</p>
        <h2>Some things aren’t for the feed.</h2>
        <Link href="/premium" className="primaryCta" onClick={() => track("premium_cta_click", { placement: "home_closing" })}>
          See what’s private
        </Link>
      </section>
    </main>
  );
}
